name: Release lib-version

on: 
  push:
    tags: 
      - "v*.*.*"
      - "v*.*.*-pre*-*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                ref: ${{ github.ref }}    # The exact tag being released
                fetch-depth: 0            # Get full history for version checking

            - name: Set up Python 3.12.2
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install setuptools wheel twine

            - name: Install build tools
              run: |
                  python -m pip install --upgrade pip build twine
           
            - name: Build package
              run: |
                  python setup.py sdist bdist_wheel
                
            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  dist/*.whl
                  dist/*.tar.gz
              env:
                GITHUB_TOKEN: ${{ secrets.WRITE_PERMISSION }}